import ignores from './ignores.mjs';

export default {
  dictionaries: ['node', 'npm', 'softwareTerms', 'typescript'],
  ignorePaths: [...ignores, '**/docs/**'],
  language: 'en,fr',
  words: [
    'basenames',
    'dotify',
    'ecycle',
    'ehook',
    'eio',
    'enoplugin',
    'envname',
    'eparse',
    'evalidate',
    'evalidation',
    'ewrite',
    'factice',
    'globaldir',
    'lifecycles',
    'morsel',
    'myapp',
    'myapp',
    'oclio',
    'oclka',
    'otherapp',
    'remerge',
    'remerged',
    'toctou',
    'unflatten',
    'unflattened',
    'unshifts',
    'unsub',
    'watchconfig',
  ],
};
