sonar.projectKey=oclkadev_morsel_accessors
sonar.organization=oclkadev

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.spec.ts
sonar.coverage.exclusions=**/__tests__/**,**/*.spec.ts,**/__e2e__/**,**/index.ts,**/types.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
