sonar.projectKey=oclkadev_morsel_core
sonar.organization=oclkadev

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.spec.ts
sonar.coverage.exclusions=**/__tests__/**,**/*.spec.ts,src/**/__e2e__/**,src/index.ts,src/**/types.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
